[build-system]
requires = [
    "setuptools>=45",
    "pip-tools >=6.4.0"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
# regex
exclude = '''
/(
  \.git
)/
'''
